# Generated by Django 2.1.7 on 2019-03-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spayce', '0002_order_receipt_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_value',
            field=models.FloatField(null=True),
        ),
    ]
