# Generated by Django 2.1.7 on 2019-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spayce', '0003_auto_20190320_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacer',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
